sudo: false

language: java

jdk: oraclejdk8

install: true

script: 
    - gradle test

notifications:
    irc:
        channels:
            - "irc.esper.net#hyperfresh"
        on_success: always
        on_failure: always
